### ISSUE TITLE
Tapping issue

### ISSUE THREAD

**Issue by mbeganovic3** [nkomirisetti/MinuteWinners#1]
For the tapping game, if I tap too fast such as a double-tap, it zooms in. Not sure if that affects the points but it seems like it doesn't register it as a tap. I am also on android so it might be different for iPhones. Also, the voiceover is great but there could be a little more detail between games saying something like "wait till we say start to play the next game" because of course, a blind person will not see the screen change to the next game. I know this is said at the beginning but maybe you can add it between too.

**Comment by KevinLane36** [comment]
This is great feedback, thank you!
We will look into the tapping issue and see if we can address that!
Adding that voiceover detail will be easy. Thanks for that feedback!

**Comment by nkomirisetti** [comment]
We should have hopefully fixed this issue, can you try it now?

**Comment by mbeganovic3** [comment]
Sorry for the late response, but yeah it works now.
