### ISSUE TITLE
Only played tapping game 3 times

### ISSUE THREAD

**Issue by benknoble** [nkomirisetti/MinuteWinners#3]
The first 3 games I got were the tapping, and then I gave up waiting for the other games.

One way to address this would be to guarantee that you don't pick the same game twice in a row, and all 3 games are chosen every 3 games... i.e., pick an order for 3 games and run that.

Update: on the 4th try, I got dance. Point still stands.

**Comment by KevinLane36** [comment]
This is very helpful feedback, thank you! 
Yes this should be an easy fix.

**Comment by KevinLane36** [comment]
Fixed!
